markdown: rdiscount
pygments: true
permalink: /posts/:year:month:day:title
rdiscount:
  extensions: [smart]
name: NRS529 URISciComp
url: http://jwhollister.com/SciComp2014
description: "NRS 529: Scientific Computing for Coastal Resources Management"
twitter: 
github: 
gravatar_url: http://www.edc.uri.edu/nrs/classes/nrs592/CI.jpg"
baseurl: /SciComp2014
comments: true